sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t isaacloft0907/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true isaacloft0907/complex-test npm test -- --coverage

after_success:
  - docker build -t isaacloft0907/client ./client
  - docker build -t isaacloft0907/server ./server
  - docker build -t isaacloft0907/nginx ./nginx
  - docker build -t isaacloft0907/worker ./worker
 # push above to docker hub, login required

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push isaacloft0907/client
  - docker push isaacloft0907/server
  - docker push isaacloft0907/nginx
  - docker push isaacloft0907/worker



  