sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t isaac/complex-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true isaac/complex-test npm test -- --coverage

after_success:
  - docker build -t isaac/client ./client/Dockerfile.dev
  - docker build -t isaac/server ./server/Dockerfile.dev
  - docker build -t isaac/nginx ./nginx/Dockerfile.dev
  - docker build -t isaac/worker ./worker/Dockerfile.dev
 # push above to docker hub, login required

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push isaac/client
  - docker push isaac/server
  - docker push isaac/nginx
  - docker push isaac/worker



  